import type { Metadata } from "next"

import { ThemeProvider } from "@/components/theme-provier"

import "@/styles/globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode
  modal: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="min-h-screen max-w-300 mx-auto">
            {modal}
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
