import type { Metadata } from "next"
import { BBH_Bogle } from "next/font/google"
import { ThemeProvider } from "@/components/theme-provier"
import "@/styles/globals.css"

const bbh_bogle = BBH_Bogle({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  adjustFontFallback: false,
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode
  modal: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${bbh_bogle.className}`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {modal}
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
